#!/bin/bash

set="${1:-1}"
cmd="./spid --signdb=./test/signdb ./test/$set.pcap"
echo "$cmd"

time $cmd 2> ./test/last.txt
cat ./test/last.txt

if [[ -f test/$set.txt ]]; then
	if diff -u test/$set.txt test/last.txt; then
		echo OK
	else
		echo FAIL
	fi
else
	mv test/last.txt test/$set.txt
	echo FIRST
fi
