#!/bin/bash
# TODO: in C / something faster?
# TODO: integrate in socketdump?

istcp=()
isok=()

while read line; do
	set -- $line

	pid="$1"
	time="$2"
	fun="$3"
	res="$4"
	fd="$5"

	case "$fun" in
		socket)
			[ $res -ge 0 ] || continue

			if [ "$6" = "SOCK_STREAM" ]; then
				istcp[$res]=1
			else
				istcp[$res]=0
			fi

			isok[$res]=1
			;;

		close)
			[ $fd -ge 0 ] || continue
			isok[$fd]=0
			;;

		# TODO: bind, accept, connect, recvfrom, sendto <- IPs and ports
		read|recv*|write|send*)
			[ $fd -ge 0 ] || continue
			[ "${isok[$fd]}" = "1" ] || continue

			echo $line
			;;
	esac
done
