#!/bin/bash
#
# Quick & dirty ptrace() IP sniffer using strace and sed
#

if [ -z "$1" ]; then
	echo "Usage: socketdump <pid>|<program...>" >&2
	exit 1
elif [[ "$1" =~ ^[0-9]+$ ]]; then
	arg="-p $1"

	# ignore already opened UNIX (netstat -x) sockets
	for socket in `netstat -xnp 2>/dev/null | grep "$1/" | awk '{print $7}'`; do
		fd=`ls -l "/proc/$1/fd" | grep "socket:\[$socket\]" | awk '{print $8}'`
		if [[ -n "$fd" ]]; then
			ignores="$ignores|$fd"
		fi
	done

	ignores="${ignores:1}"
	echo "ignored fds: $ignores" >&2
else
	arg="-- $@"
fi

strace -fqtttvxx -s 12 -e network,read,write,close $arg 2>&1 \
	| sed -r \
		-e '/(EAGAIN|SOL_SOCKET|SIG_|msg|MSG_PEEK|FILE|NETLINK|getsockname|unfinished|resumed)/d' \
		-e 's/,//g' -e 's/[\{\[\}]//g' -e 's/\.\.\.//g' -e 's/]//g' \
		-e 's/=htons/=/g' -e 's/=inet_addr/=/g' \
		-e 's/^[^0-9]*([0-9]+)[^0-9]+([0-9.]+) ([a-z]+)\((.*)\)[ ]+= ([-0-9]+)/\1 \2 \3 \5 \4/g' \
		-e 's/[\(\)]//g' -e 's/"x/"/g' -e 's/x/ /g' -e '/ (read|write|recv|send|sendto|recvfrom) [0-9] /d' \
		${ignores:+-e "/ (read|write) [0-9]+ ($ignores) /d"}

#		-e 's/^[^0-9]*([0-9]+)[^0-9]+([0-9.]+) ([a-z]+)\((.*) <unfinished.*/\1 \2 \3 unfinished \4/g' \
#		-e 's/^[^0-9]*([0-9]+)[^0-9]+([0-9.]+) < ([a-z]+) resumed> (.*)\)[ ]+= ([-0-9]+).*/\1 \2 \3 resumed \5 \4/g' \
